#!/bin/bash
#
# Copyright 2016 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

ROOT=$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")

# Set up the ESP submodules.
git -C "${ROOT}" submodule update --init --recursive

COMMIT_MSG='https://gerrit-review.googlesource.com/tools/hooks/commit-msg'

function install_hook() {
  local GIT_DIR="$(git -C "${1}" rev-parse --git-dir)"
  curl -Lo "${GIT_DIR}/hooks/commit-msg" "${COMMIT_MSG}" \
    && chmod +x "${GIT_DIR}/hooks/commit-msg"
}

install_hook "${ROOT}"

for repo in .; do
  ORIGIN=$(git -C "${ROOT}/${repo}" config remote.origin.url)
  git -C "${ROOT}/${repo}" config remote.review.pushurl ${ORIGIN}
  git -C "${ROOT}/${repo}" config remote.review.push HEAD:refs/for/master
  git -C "${ROOT}/${repo}" config remote.draft.pushurl ${ORIGIN}
  git -C "${ROOT}/${repo}" config remote.draft.push HEAD:refs/drafts/master
done